services:
  backend:
    # Change this path to match exactly where your manage.py and Dockerfile are
    build: ./backend/backend_project_folder
    volumes:
      - ./backend/backend_project_folder:/app/backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    stdin_open: true