# Generated by Django 5.2.8 on 2026-01-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='carousel_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
