# Generated by Django 5.2.8 on 2026-01-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_sitesettings_about_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_text',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_section',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
