# Generated by Django 5.2.8 on 2026-02-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_remove_sitesettings_about_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
